[package]
name = "echo"
authors = ["adwd <adwd@users.noreply.github.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[workspace]
